{{- $namespace := include "namespace" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $namespace }}
data:
  teamName: {{ .Values.teamName }}
  region: {{ .Values.region }}
  environment: {{ .Values.environment }}
  apptioId: {{ .Values.apptioId }}
{{- if .Values.allowedHosts }}
  allowedHosts:
  {{- range .Values.allowedHosts }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
{{- if .Values.allowedDomains }}
  allowedDomains:
  {{- range .Values.allowedDomains }}
    - {{ . | quote }}
  {{- end }}
{{- end }}