{{- $namespace := include "namespace" . -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contributor-role-binding
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: contributor
  namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: contributor
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: reader-role-binding
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: reader
  namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io