{{- $namespace := include "namespace" . -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: contributor
  namespace: {{ $namespace }}
rules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - ""
    resources:
      - pods
      - pods/log
      - configmaps
      - endpoints
      - services
      - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
    - extensions
    - apps
    resources:
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
    - batch
    - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - ingresses
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
    - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
    - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
    - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: reader
  namespace: {{ $namespace }}
rules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
      - pods
      - pods/log
      - configmaps
      - endpoints
      - services
      - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
  - apiGroups:
    - extensions
    - apps
    resources:
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - batch
    - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - ingresses
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---