{{- $namespace := include "namespace" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader
  namespace: {{ $namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: contributor
  namespace: {{ $namespace }}