apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v1
    appVersion: v0.1.0
    created: "2020-01-30T10:14:39.4732449-05:00"
    description: A Helm chart for cert-manager
    digest: 9e8b98f4ddc1083cc6aaadc3df3580b8838bc404edaf3f97c3c601410818ef6d
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/cert-manager/cert-manager-v0.1.0.tgz
    version: v0.1.0
  fluent-bit:
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2020-01-30T10:14:39.4792474-05:00"
    description: Uses fluent-bit Loki go plugin for gathering logs and sending them
      to Loki
    digest: b83f1c52b7bb25264f44b59fc2e5dfcdcc23876245fe1332fc84290668d4055c
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: fluent-bit
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/fluent-bit/fluent-bit-0.0.5.tgz
    version: 0.0.5
  grafana:
  - apiVersion: v1
    appVersion: 6.5.2
    created: "2020-01-30T10:14:39.4872448-05:00"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 74dfd21deb064681094fbe4bc3f9a7e9b20093ed6e691983575cb36e084bd268
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/grafana/grafana-4.4.0.tgz
    version: 4.4.0
  loki:
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2020-01-30T10:14:39.4922457-05:00"
    description: 'Loki: like Prometheus, but for logs.'
    digest: c9d70169f807c585a2d0d5786d62664414b712c5ee7062a2cefb236d74eaf258
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/loki/loki-0.25.0.tgz
    version: 0.25.0
  nginx-ingress:
  - apiVersion: v1
    appVersion: 0.28.0
    created: "2020-01-30T10:14:39.5002465-05:00"
    description: An nginx Ingress controller that uses ConfigMap to store the nginx
      configuration.
    digest: a9944db984700a87f0b72bde50256bc8088997aeabdf4d3d0a88b5b1c15735fc
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.10.0-0'
    maintainers:
    - name: ChiefAlexander
    - email: Trevor.G.Wood@gmail.com
      name: taharah
    name: nginx-ingress
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/nginx-ingress/nginx-ingress-1.29.6.tgz
    version: 1.29.6
  onboard:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-01-30T10:14:39.5002465-05:00"
    description: A Helm chart for Kubernetes
    digest: 0d3b32b9a8002ae0022349edb4c38ec8c60257f4a7df4df547e511e04952d79d
    name: onboard
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/onboard/onboard-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-01-30T10:14:39.5092479-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: aaed32c36762e65c478b7aa0256440b23c7e5c22aaec55ccef4e52ea9335e8cc
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/prometheus/prometheus-10.3.1.tgz
    version: 10.3.1
  promtail:
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2020-01-30T10:14:39.5152488-05:00"
    description: Responsible for gathering logs and sending them to Loki
    digest: d59ab482981d7b14bcb885d79e1e15b28f7881c906471efc67e88dec7307b67c
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/master/charts/promtail/promtail-0.17.0.tgz
    version: 0.17.0
generated: "2020-01-30T10:14:39.465246-05:00"
