apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v1
    appVersion: v0.1.0
    created: "2020-02-04T23:26:48.9354944-05:00"
    description: A Helm chart for cert-manager
    digest: 9e8b98f4ddc1083cc6aaadc3df3580b8838bc404edaf3f97c3c601410818ef6d
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/cert-manager/cert-manager-v0.1.0.tgz
    version: v0.1.0
  fluent-bit:
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2020-02-04T23:26:48.9429696-05:00"
    description: Uses fluent-bit Loki go plugin for gathering logs and sending them
      to Loki
    digest: b83f1c52b7bb25264f44b59fc2e5dfcdcc23876245fe1332fc84290668d4055c
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: fluent-bit
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/fluent-bit/fluent-bit-0.0.5.tgz
    version: 0.0.5
  grafana:
  - apiVersion: v1
    appVersion: 6.5.2
    created: "2020-02-04T23:26:48.9514494-05:00"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 74dfd21deb064681094fbe4bc3f9a7e9b20093ed6e691983575cb36e084bd268
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/grafana/grafana-4.4.0.tgz
    version: 4.4.0
  linkerd2:
  - apiVersion: v1
    appVersion: edge-20.1.1
    created: "2020-02-04T23:26:48.9596491-05:00"
    dependencies:
    - name: partials
      repository: file://../partials
      version: 0.1.0
    description: Linkerd gives you observability, reliability, and security for your
      microservices — with no code change required.
    digest: a73befd15814732bc6ce9ec7b7fefb04bcf2d93055a30d10c43a36eeeff9fc94
    home: https://linkerd.io
    icon: https://linkerd.io/images/logo-only-200h.png
    keywords:
    - service-mesh
    kubeVersion: '>=1.13.0-0'
    maintainers:
    - email: cncf-linkerd-dev@lists.cncf.io
      name: Linkerd authors
      url: https://linkerd.io/
    name: linkerd2
    sources:
    - https://github.com/linkerd/linkerd2/
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/linkerd2/linkerd2-0.1.1.tgz
    version: 0.1.1
  loki:
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2020-02-04T23:26:48.9668439-05:00"
    description: 'Loki: like Prometheus, but for logs.'
    digest: c9d70169f807c585a2d0d5786d62664414b712c5ee7062a2cefb236d74eaf258
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/loki/loki-0.25.0.tgz
    version: 0.25.0
  loki-stack:
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2020-02-04T23:26:48.9797622-05:00"
    dependencies:
    - condition: loki.enabled
      name: loki
      repository: file://../loki
      version: ^0.6.0
    - condition: promtail.enabled
      name: promtail
      repository: file://../promtail
      version: ^0.6.0
    - condition: fluent-bit.enabled
      name: fluent-bit
      repository: file://../fluent-bit
      version: ^0.0.1
    description: 'Loki: like Prometheus, but for logs.'
    digest: a0f3786f9fe980af1671dc04c677c7c7af9fb7601c5d0fd507c90d46fb4dacf2
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/loki-stack/loki-stack-0.30.0.tgz
    version: 0.30.0
  nginx-ingress:
  - apiVersion: v1
    appVersion: 0.28.0
    created: "2020-02-04T23:26:48.9888126-05:00"
    description: An nginx Ingress controller that uses ConfigMap to store the nginx
      configuration.
    digest: a9944db984700a87f0b72bde50256bc8088997aeabdf4d3d0a88b5b1c15735fc
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.10.0-0'
    maintainers:
    - name: ChiefAlexander
    - email: Trevor.G.Wood@gmail.com
      name: taharah
    name: nginx-ingress
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/nginx-ingress/nginx-ingress-1.29.6.tgz
    version: 1.29.6
  onboard:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.0075823-05:00"
    description: A Helm chart for Kubernetes
    digest: 6cdcaf9997e084000dfe3caf436de08a99063d7cee60bd3fed5ccb4c2c68e121
    name: onboard
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/onboard/onboard-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.0075823-05:00"
    description: A Helm chart for Kubernetes
    digest: 8f260f2bde7ebfc01e4df9e15f626d59584958c75e597339569ad7136d0e5a5a
    name: onboard
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/onboard/onboard-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.0015572-05:00"
    description: A Helm chart for Kubernetes
    digest: 97dbddfb708cf9fa124bba57bd34f384a4545d0fa8cefeea47c34d66d27c51fb
    name: onboard
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/onboard/onboard-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:48.9943434-05:00"
    description: A Helm chart for Kubernetes
    digest: 0d3b32b9a8002ae0022349edb4c38ec8c60257f4a7df4df547e511e04952d79d
    name: onboard
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/onboard/onboard-0.1.0.tgz
    version: 0.1.0
  partials:
  - apiVersion: v1
    created: "2020-02-04T23:26:49.0141745-05:00"
    description: A Helm chart containing Linkerd partial templates, depended by the
      'linkerd' and 'patch' charts.
    digest: 8ecf65b82703ebe901a8b12a83cd18b428a31bf035d55e7ea9a29ce5a652ba36
    name: partials
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/partials/partials-0.1.0.tgz
    version: 0.1.0
  policy:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.027432-05:00"
    description: A Helm chart for policy deployment
    digest: 3aacf205989592cdaf3c7b79c6cbccdcdc72021b3422d6a32a032c8f12fb780f
    name: policy
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/policy/policy-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.0208332-05:00"
    description: A Helm chart for policy deployment
    digest: 0337be2e5ed9f09b46bb0e33986b845be757f87e7a0dd0dfcdd91f23e6ddc5e5
    name: policy
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/policy/policy-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-02-04T23:26:49.0947883-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: 98a0cfb1597f6372798242c66fc32c5ac14d9d2d7f9fb5098cfc8840f1c177b2
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/prometheus/prometheus-10.3.6.tgz
    version: 10.3.6
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-02-04T23:26:49.0847115-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: 7e6f6babc063ba9690bd43d0c11eb8ace4cddea917794533488822dd6b1fc53d
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/prometheus/prometheus-10.3.5.tgz
    version: 10.3.5
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-02-04T23:26:49.0735123-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: 1a9aea60b2859ed4abce2a3164af2b637c9855ea94a3b0dc1bb4762f40991141
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/prometheus/prometheus-10.3.4.tgz
    version: 10.3.4
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-02-04T23:26:49.0604649-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: 57ea642c5812e25829d812452c1cd23b8cb6ceb242b4edacb072bda16209e1b5
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/prometheus/prometheus-10.3.3.tgz
    version: 10.3.3
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-02-04T23:26:49.0494183-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: 3c1f7aeb2389f778a83fd17096bfb56ea4c70d95ac114457b7fc9caf1b5b815c
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/prometheus/prometheus-10.3.2.tgz
    version: 10.3.2
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2020-02-04T23:26:49.0394165-05:00"
    description: Prometheus is a monitoring system and time series database.
    digest: aaed32c36762e65c478b7aa0256440b23c7e5c22aaec55ccef4e52ea9335e8cc
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/prometheus/prometheus-10.3.1.tgz
    version: 10.3.1
  promtail:
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2020-02-04T23:26:49.1023141-05:00"
    description: Responsible for gathering logs and sending them to Loki
    digest: d59ab482981d7b14bcb885d79e1e15b28f7881c906471efc67e88dec7307b67c
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/promtail/promtail-0.17.0.tgz
    version: 0.17.0
  thanos:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.1133447-05:00"
    description: A Helm chart for Thanos Querier
    digest: b7e64f4a714240b28dc535394d9b17625bb8cacb0be91e90a2f9a1e804c534f2
    name: thanos
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/thanos/thanos-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-04T23:26:49.1083808-05:00"
    description: A Helm chart for Thanos Querier
    digest: 7d1d67a595a08fd1342afcfcdc00bdabe9b74ec112b331b792f4d0097134bc7a
    name: thanos
    urls:
    - https://ramakrishnateja.github.io/msready-charts/charts/thanos/thanos-0.1.0.tgz
    version: 0.1.0
generated: "2020-02-04T23:26:48.9262688-05:00"
