apiVersion: v1
kind: Service
metadata:
  name: policy-service
spec:
  selector:
    app: policy-service-nginx
  ports:
    - port: 443
      targetPort: https
      name: https
      protocol: TCP
  type: ClusterIP