dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "file://../loki"
  version: "^0.6.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "file://../promtail"
  version: "^0.6.0"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "file://../fluent-bit"
  version: "^0.0.1"
